export interface DocumentPolicy {
  allowedRoles: string[];
  allowedDocumentTypes: string[];
  allowedCategories: string[];
  allowedMimeTypes: string[];
  maxSizeBytes: number;
  bucket: string;
  accessLevel: 'public' | 'private' | 'role_restricted';
  supportsPendingEntity: boolean;
}

export const DOCUMENT_POLICIES: Record<string, DocumentPolicy> = {
  expenses: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['expense_receipt', 'expense_invoice', 'payment_proof'],
    allowedCategories: ['receipt', 'invoice', 'evidence'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  purchases: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['purchase_quotation'],
    allowedCategories: ['document', 'evidence'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  goods_receipts: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['delivery_challan', 'goods_received_photo'],
    allowedCategories: ['document', 'evidence', 'media'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  supplier_invoices: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['supplier_invoice'],
    allowedCategories: ['invoice'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  supplier_payments: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['payment_proof'],
    allowedCategories: ['evidence'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  wastage_events: {
    allowedRoles: ['owner', 'admin', 'manager', 'kitchen'],
    allowedDocumentTypes: ['wastage_photo'],
    allowedCategories: ['media', 'evidence'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  stock_adjustments: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['count_sheet', 'damage_photo'],
    allowedCategories: ['document', 'media', 'evidence'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true,
  },
  refund_requests: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['refund_evidence', 'refund_payment_proof'],
    allowedCategories: ['evidence'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  approval_requests: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['supporting_document', 'quotation', 'count_sheet'],
    allowedCategories: ['evidence', 'document'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  cash_sessions: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['closing_proof', 'upi_settlement', 'digital_report'],
    allowedCategories: ['evidence', 'report'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  complaints: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['customer_evidence', 'manager_inspection_evidence'],
    allowedCategories: ['evidence', 'media'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  staff_leave: {
    allowedRoles: ['owner', 'admin', 'manager', 'kitchen', 'rider', 'cashier'],
    allowedDocumentTypes: ['leave_document'],
    allowedCategories: ['document'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  delivery_orders: {
    allowedRoles: ['owner', 'admin', 'manager', 'rider'],
    allowedDocumentTypes: ['proof_of_delivery'],
    allowedCategories: ['evidence', 'media'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  maintenance_records: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['before_photo', 'after_photo', 'technician_invoice', 'warranty_document', 'payment_proof'],
    allowedCategories: ['evidence', 'media', 'document', 'invoice'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  corrective_tasks: {
    allowedRoles: ['owner', 'admin', 'manager', 'kitchen', 'cashier'],
    allowedDocumentTypes: ['before_evidence', 'after_evidence'],
    allowedCategories: ['evidence', 'media'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: false,
  },
  general_documents: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: [
      'supplier_invoice', 'purchase_invoice', 'expense_receipt', 
      'expense_invoice', 'quotation', 'delivery_challan', 
      'payment_proof', 'compliance_certificate', 'staff_document', 
      'maintenance_invoice', 'general_document'
    ],
    allowedCategories: ['invoice', 'receipt', 'evidence', 'document', 'report'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    maxSizeBytes: 50 * 1024 * 1024,
    bucket: 'ilara-private-files',
    accessLevel: 'private',
    supportsPendingEntity: true, 
  },
  menu_items: {
    allowedRoles: ['owner', 'admin', 'manager'],
    allowedDocumentTypes: ['menu_image'],
    allowedCategories: ['menu', 'media'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxSizeBytes: 10 * 1024 * 1024,
    bucket: 'ilara-public-media',
    accessLevel: 'public',
    supportsPendingEntity: true,
  },
  outlets: {
    allowedRoles: ['owner', 'admin'],
    allowedDocumentTypes: ['atmosphere_image', 'logo'],
    allowedCategories: ['atmosphere', 'media'],
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxSizeBytes: 20 * 1024 * 1024,
    bucket: 'ilara-public-media',
    accessLevel: 'public',
    supportsPendingEntity: false,
  }
};
